return {
  phpantom = {
    cmd = { '/home/hollow3464/.local/bin/phpantom_lsp' },
    filetypes = { 'php', 'blade' },
    root_markers = { 'composer.json', '.git' },
  },
  intelephense = {
    filetypes = { 'php', 'blade' },
    settings = {
      intelephense = {
        stubs = {
          'apcu',
          'apache',
          'bcmath',
          'bz2',
          'calendar',
          'com_dotnet',
          'Core',
          'ctype',
          'curl',
          'date',
          'dba',
          'dom',
          'enchant',
          'exif',
          'FFI',
          'fileinfo',
          'filter',
          'fpm',
          'ftp',
          'gd',
          'gettext',
          'gmp',
          'hash',
          'iconv',
          'imap',
          'intl',
          'json',
          'ldap',
          'libxml',
          'mbstring',
          'meta',
          'mysqli',
          'oci8',
          'odbc',
          'openssl',
          'pcntl',
          'pcre',
          'PDO',
          'pdo_ibm',
          'pdo_mysql',
          'pdo_pgsql',
          'pdo_sqlite',
          'pgsql',
          'Phar',
          'posix',
          'pspell',
          'readline',
          'Reflection',
          'redis',
          'session',
          'shmop',
          'SimpleXML',
          'snmp',
          'soap',
          'sockets',
          'sodium',
          'SPL',
          'sqlite3',
          'standard',
          'superglobals',
          'sysvmsg',
          'sysvsem',
          'sysvshm',
          'tidy',
          'tokenizer',
          'xml',
          'xmlreader',
          'xmlrpc',
          'xmlwriter',
          'xsl',
          'Zend OPcache',
          'opcache',
          'zip',
          'zlib',
        },
      },
    },
  },
}
